### ISSUE TITLE
viewBox attr should contain uppercase 'B'

### ISSUE THREAD

**Issue by seanrmurphy** [nathanhack/svg#1]
In the SVG definition, the viewBox attribute contains uppercase 'B':

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox

In the lib, there is a lowercase 'b' used in this attribute definition:

https://github.com/nathanhack/svg/blob/master/attr/attributes.go#L1142

**Comment by nathanhack** [comment]
From the the mozilla link you provided it says :
`The value of the viewBox attribute is a list of four numbers: min-x, min-y, width and height.`
And from what I can tell it makes no mention of a variable or value called `B`.

Checking https://www.w3.org/TR/SVG2/coords.html#ViewBoxAttribute it also only shows the four number values. 

That said if something is missing, I'll be glad to add it, or approve a PR.

**Comment by seanrmurphy** [comment]
Apols - was not v clear - did not want to make PR for one character change although it may have been quicker...

This line

https://github.com/nathanhack/svg/blob/master/attr/attributes.go#L1142

should be:

`N: "viewBox",`

with an uppercase B.

**Comment by nathanhack** [comment]
Wholly smokes, sorry I didn't understand what you were saying. But now it's all clear.
Yeah I understand doing a PR for one character change seems a bit much but a issue ticket is perfect.
One sec and I'll fix it.

**Comment by nathanhack** [comment]
If there are others let me know. I'll be glad to fix them.

**Comment by seanrmurphy** [comment]
I'm only experimenting with it to see what is possible. I did add some abstractions to the `path` definitions in my local copy and provide helper functions to generate the textual representation of the path - I can share this with you if you think it might be interesting.

**Comment by nathanhack** [comment]
Adding something to help build paths is on my list. I haven't gotten to it yet.
If you are willing to share, I'd definitely be interested.
